theme: jekyll-theme-cayman

title: "SAM-FP: Graphical User Interface"
author: "Bruno C. Quint"
description: "A Qt GUI for the SAM-FP observation mode at the SOAR Telescope."
show_downloads: true

repository_url: "https://github.com/b1quint/samfp_gui/tree/samfp_v0.1"
zip_url: "https://github.com/b1quint/samfp_gui/archive/samfp-gui_v0.1.zip"
tar_url: "https://github.com/b1quint/samfp_gui/archive/samfp-gui_v0.1.tar.gz"

