#!python

from samfp_gui.gui import Main
from PyQt4 import QtGui

import sys
import pkg_resources

if __name__ == "__main__":

    icon_path = pkg_resources.resource_filename(
        'samfp_gui', 'icons/load-file.png')
    print(icon_path)

    app = QtGui.QApplication(sys.argv)
    ex = Main()
    sys.exit(app.exec_())

