#!python

from samfp_gui.gui import MainWindow
from PyQt5 import QtWidgets

import sys

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    ex = MainWindow()
    sys.exit(app.exec_())

