#!python

from samfp_gui.gui import Main
from PyQt5 import QtWidgets

import sys
import pkg_resources

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    ex = Main()
    sys.exit(app.exec_())

