# Custom methods ---
from .scan import do_scan
from .scan import expose
from .scan import fp_moveabs
from .scan import send_command
from .scan import set_comment
from .scan import set_image_basename
from .scan import set_image_exposure_time
from .scan import set_image_path
from .scan import set_image_nframes
from .scan import set_image_type
from .scan import set_target_name
from .scan import set_scan_id
from .scan import set_scan_nchannels
from .scan import set_scan_start
from .scan import set_scan_current_sweep
from .scan import set_scan_current_z